### ISSUE TITLE
Register script tags with attributes

### ISSUE THREAD

**Issue by igbanam** [yiisoft/assets#90]
When registering JS files, I'd like to register them with assets. According to [the documentation][1], it's possible to declare JS files with options as HTML attributes — save a few. Doing this causes an issue when converting the JS file. #89 attempts to fix this, but needs some touching up to ensure it builds properly

### What steps will reproduce the problem?

In `src/Asset/AppAsset.php` declare JS files as 

```php
    public array $js = [
        'js/site.js' => [
            'foo' => 'bar',
        ]
    ];
```

### What is the expected result?

```html
<script src="/assets/br34d3d/js/site.js" foo="bar"></script>
```

### What do you get instead?

```
Yiisoft\ErrorHandler\Exception\ErrorException: Undefined array key 0 in /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/assets/src/AssetRegistrar.php:246
Stack trace:
#0 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/assets/src/AssetRegistrar.php(246): Yiisoft\ErrorHandler\ErrorHandler::Yiisoft\ErrorHandler\{closure}(2, 'Undefined array...', '/Users/igbanam/...', 246)
#1 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/assets/src/AssetRegistrar.php(143): Yiisoft\Assets\AssetRegistrar->convertJs(Object(App\Asset\AppAsset))
#2 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/assets/src/AssetManager.php(394): Yiisoft\Assets\AssetRegistrar->register(Object(App\Asset\AppAsset))
#3 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/assets/src/AssetManager.php(256): Yiisoft\Assets\AssetManager->registerFiles('App\\Asset\\AppAs...')
#4 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/assets/src/AssetManager.php(272): Yiisoft\Assets\AssetManager->register('App\\Asset\\AppAs...', NULL, NULL)
#5 /Users/igbanam/projects/igbanam/memscape/resources/views/layout/main.php(23): Yiisoft\Assets\AssetManager->registerMany(Array)
#6 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/view/src/PhpTemplateRenderer.php(28): require('/Users/igbanam/...')
#7 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/view/src/PhpTemplateRenderer.php(37): Yiisoft\View\PhpTemplateRenderer->Yiisoft\View\{closure}('/Users/igbanam/...', Array)
#8 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/view/src/ViewTrait.php(449): Yiisoft\View\PhpTemplateRenderer->render(Object(Yiisoft\View\WebView), '/Users/igbanam/...', Array)
#9 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/yii-view/src/ViewRenderer.php(339): Yiisoft\View\WebView->renderFile('/Users/igbanam/...', Array)
#10 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/yii-view/src/ViewRenderer.php(119): Yiisoft\Yii\View\ViewRenderer->renderProxy('index', Array, Array, Array, Array, Array)
#11 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/data-response/src/DataResponse.php(324): Yiisoft\Yii\View\ViewRenderer->Yiisoft\Yii\View\{closure}()
#12 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/data-response/src/Formatter/HtmlDataResponseFormatter.php(43): Yiisoft\DataResponse\DataResponse->getData()
#13 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/data-response/src/DataResponse.php(353): Yiisoft\DataResponse\Formatter\HtmlDataResponseFormatter->format(Object(Yiisoft\DataResponse\DataResponse))
#14 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/data-response/src/DataResponse.php(146): Yiisoft\DataResponse\DataResponse->formatResponse()
#15 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/yii-debug/src/Collector/RequestCollector.php(48): Yiisoft\DataResponse\DataResponse->getStatusCode()
#16 [internal function]: Yiisoft\Yii\Debug\Collector\RequestCollector->collect(Object(Yiisoft\Yii\Http\Event\AfterRequest))
#17 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/injector/src/Injector.php(66): ReflectionFunction->invokeArgs(Array)
#18 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/yii-event/src/ListenerCollectionFactory.php(54): Yiisoft\Injector\Injector->invoke(Object(Closure), Array)
#19 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/event-dispatcher/src/Dispatcher/Dispatcher.php(34): Yiisoft\Yii\Event\ListenerCollectionFactory->Yiisoft\Yii\Event\{closure}(Object(Yiisoft\Yii\Http\Event\AfterRequest))
#20 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/yii-debug/src/Proxy/EventDispatcherInterfaceProxy.php(25): Yiisoft\EventDispatcher\Dispatcher\Dispatcher->dispatch(Object(Yiisoft\Yii\Http\Event\AfterRequest))
#21 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/yii-http/src/Application.php(89): Yiisoft\Yii\Debug\Proxy\EventDispatcherInterfaceProxy->dispatch(Object(Yiisoft\Yii\Http\Event\AfterRequest))
#22 /Users/igbanam/projects/igbanam/memscape/vendor/yiisoft/yii-runner-http/src/HttpApplicationRunner.php(209): Yiisoft\Yii\Http\Application->handle(Object(HttpSoft\Message\ServerRequest))
#23 /Users/igbanam/projects/igbanam/memscape/public/index.php(35): Yiisoft\Yii\Runner\Http\HttpApplicationRunner->run()
#24 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0
| PHP version      |  8.1
| Operating system | OS X

**Comment by vjik** [comment]
Use this syntax:

```php
public array $js = [
	['js/site.js', 'foo' => 'bar'],
];
```
